### PR TITLE
37 ds delete category

### PR DESCRIPTION
**Pull request by DougSilvera**
#### Changes Made
1. Added file `categoryDelete.js` to `src/components/Categories` directory.
1. Modified file `categoryManager.js` to include `deleteCategory` function.
2. Modified `ApplicationViews.Js` to include routing for delete confirmation view

​
#### Steps to Review
1. Checkout this branch locally.
    ```
    git fetch --all
    git checkout 37_DS_delete_category
    ```
4. Open a new Terminal tab (⌘T) and navigate to the server directory.
5. Test app functionality.
    > when a logged in user selects the delete link in the category list they are redirected to a confirmation page with the corresponding category name. when the delete button is clicked the data is removed and the user is redirected back to the category list
6. View code file.
    > Confirm file modifications are present as indicated above.
    > Confirm no unused code or extraneous comments exist.

### CODE REVIEW

**Comment by DougSilvera** [comment]
STEPS TO UPDATE

run the INSERT sql query for the category table
using post table designer set the default value of CategoryId to the id of the newly inserted category

run the 2 alter table queries, this will set the on delete to `SET DEFAULT` for for the categoryid on the post table

now when a category is deleted that is in use by a post it will automatically be set to NO CATEGORY

**Comment by SharifRashed** [comment]
👍🏻

**Review by SharifRashed — APPROVED** [review]

**Review by joshdbarton — CHANGES_REQUESTED** [review]
My only comment is that though we are assuming everyone is an admin on the client side up until now, I think it makes sense to check if the user is an admin on the server side before allowing the delete operation to proceed.

**Comment by DougSilvera** [comment]
> My only comment is that though we are assuming everyone is an admin on the client side up until now, I think it makes sense to check if the user is an admin on the server side before allowing the delete operation to proceed.

User validation added to api for data modification methods, conditional rendering added to prevent delete and edit option for default category

**Review by joshdbarton — APPROVED** [review]

**Comment by DougSilvera** [comment]
refactored to replace `NotFound` with `Forbid` in `categoryController.cs`

**Pull request merged**
